- name: nginx install and run the server
  hosts: web
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.dnf:
     name: nginx
     state: present

 - name: run nginx
   ansible.builtin.sevice:
    name: nginx
    state: started
    enabled: yes