- name: vaiables to print
  hosts: web
  vars: # play level variables
   COuRSE: "DEVOPS WITH AWS"
   DuRATION: "120HRS"
   TRAINER: "SIVA KuMA REDDY M"
  tasks:
  - name: print te infomation
    ansible.builtin.debug:
     msg: "Hi I am trainer {{ COuRSE}}, Dration is: {{DuRATION}}, Trainer: {{TRAINER}}"