- name: variables from files
  hosts: web
  vars_files:
   -vars.yaml
  tasks: 
  - name: vaiables from the files i am getting
    ansible.builtin.debug:
     msg: "Hi I am learning {{ COuRSE }}, Dration is {{DuRATION}}, trainer is {{TRAINER}}"