- name: vaiables from the prompt
  hosts: web
  vars_prompt:
   - name: COuRSE
     prompt: Please enter the cousre name
     private: false
   - name: TRAINER
     prompt: enter the trainer name
     private: false

   - name: DuRATION
     prompt: please enter the trainer name
     private: false


  tasks:
  - name: variable from the pompt coming...
    ansible.builtin.debug:
     msg: "Hi, I am LEANING {{COuRSE}}, FROM dration is {{DuRATION}} TRAINER IS {{TRAINER}}, "