- name: use exists or not we ae checking
  hosts: web
  tasks:
  - name: user exists (or) not check
    ansible.builtin.command: id expense
    register: USER

  - name: print te infomation
    ansible.builtin.debug:
     msg: "user info: {{USER}}"

  - name: create the USER if not there
    ansible.builtin.command: useradd expense
    when: rc | int >= 1
