- name: use exists or not we ae checking
  hosts: web
  tasks:
  - name: user exists (or) not check
    ansible.builtin.command: id expense
    register: uSER

  - name: print te infomation
    ansible.builtin.debug:
     msg: "user info: {{uSER}}