- name: gathering facts
  hosts: web
  become: yes
  tasks:
   - name: print the facts
     ansible.builtin.debug:
       msg: "{{ansible_facts}}"

   - name: install nginx in redhat
     ansible.builtin.dnf:
        name: nginx
        state: present
     when: ansible_os_family == "RedHat"

   - name: install nginx in debain (or) ubuntu
     ansible.builtin.apt:
       name: nginx
       state: present
     when: ansible_os_family == "Debian"