- name: loops packages install
  hosts: web
  become: yes
  tasks: 
   - name: installing loops fom packages
     ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
     loop:
      - {name: 'mysql' , state: 'present'}
      - {name: 'nodejs' , state: 'absent'}
      - {name: 'nginx', state: 'absent'}
      - {name: 'postfix' , state: 'present'}